// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb2GG8kJrJZT8hThK_jpy1I3MIC2anJa0',
    appId: '1:940380612621:web:7301004bb480345699cd44',
    messagingSenderId: '940380612621',
    projectId: 'finally-social-app',
    authDomain: 'finally-social-app.firebaseapp.com',
    storageBucket: 'finally-social-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD4OcT8gGFjlzWJHvzCk6HgZlhNqq84to',
    appId: '1:940380612621:android:2fef14d0311c4fc599cd44',
    messagingSenderId: '940380612621',
    projectId: 'finally-social-app',
    storageBucket: 'finally-social-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCubuYVBcXpodACEG_dv5GAY11qo5-ZDdo',
    appId: '1:940380612621:ios:459f5622f57ef0f999cd44',
    messagingSenderId: '940380612621',
    projectId: 'finally-social-app',
    storageBucket: 'finally-social-app.appspot.com',
    iosBundleId: 'com.example.finallysocialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCubuYVBcXpodACEG_dv5GAY11qo5-ZDdo',
    appId: '1:940380612621:ios:459f5622f57ef0f999cd44',
    messagingSenderId: '940380612621',
    projectId: 'finally-social-app',
    storageBucket: 'finally-social-app.appspot.com',
    iosBundleId: 'com.example.finallysocialapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb2GG8kJrJZT8hThK_jpy1I3MIC2anJa0',
    appId: '1:940380612621:web:3421f1f9218bf82499cd44',
    messagingSenderId: '940380612621',
    projectId: 'finally-social-app',
    authDomain: 'finally-social-app.firebaseapp.com',
    storageBucket: 'finally-social-app.appspot.com',
  );
}
